# Generated by Django 2.1.3 on 2018-12-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtime',
            old_name='event_end',
            new_name='event_e',
        ),
        migrations.RenameField(
            model_name='eventtime',
            old_name='event_start',
            new_name='event_s',
        ),
    ]
