# Generated by Django 2.1.4 on 2018-12-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0002_auto_20181210_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtime',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_times', to='eventsapp.Events'),
        ),
    ]
