# Generated by Django 2.1.3 on 2018-12-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0002_auto_20181207_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtime',
            old_name='event_e',
            new_name='event_end_time',
        ),
        migrations.RenameField(
            model_name='eventtime',
            old_name='event_s',
            new_name='event_start_time',
        ),
    ]
