# Generated by Django 2.1.3 on 2018-12-17 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
