# Generated by Django 2.1.3 on 2018-12-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitationapp', '0002_auto_20181217_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitations',
            name='registered',
            field=models.BooleanField(default='False'),
        ),
    ]
