# Generated by Django 2.1.4 on 2018-12-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarksapp', '0003_auto_20181203_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='description',
        ),
    ]
